const db = require("./connection");
const { User, Product, Category } = require("../models");

db.once("open", async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { region: "Africa" }, // 0
    { region: "Asia" }, // 1
    { region: "Caribbean" }, // 2
    { region: "Central America" }, // 3
    { region: "Europe" }, // 4
    { region: "North America" }, //  5
    { region: "Oceania" }, // 6
    { region: "South America" }, // 7
  ]);

  console.log("categories - regions seeded");

  await Product.deleteMany();

  const products = await Product.insertMany([
    {
      packageId: "US0001",
      name: "Trip 1",
      description: "Weekend trip to New York!",
      image: "America.jpeg",
      country: "United States",
      price: 499.99,
      discount: 25,
      quantity: 20,
      rating: 4,
      departure: "2023-04-01",
      duration: 2,
      allinclusive: false,
      activities: true,
      category: categories[5]._id,
    },
    {
      packageId: "CU0001",
      name: "Trip 2",
      description: "A week vacation in Cayo Coco!",
      image: "Cuba.jpeg",
      country: "Cuba",
      price: 1099.99,
      discount: 50,
      quantity: 30,
      rating: 5,
      departure: "2023-04-04",
      duration: 7,
      allinclusive: true,
      activities: false,
      category: categories[3]._id,
    },
    {
      packageId: "FR0001",
      name: "Trip 3",
      description: "Weekend trip Paris",
      image: "France.jpeg",
      country: "France",
      price: 799.99,
      discount: 25,
      quantity: 25,
      rating: 4,
      departure: "2023-05-03",
      duration: 2,
      allinclusive: false,
      activities: true,
      category: categories[4]._id,
    },
    {
      packageId: "GE0001",
      name: "Trip 4",
      description: "Weekend trip Germany",
      image: "Germany.jpeg",
      country: "Germany",
      price: 999.99,
      discount: 25,
      quantity: 19,
      rating: 4,
      departure: "2023-06-03",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[4]._id,
    },
    {
      packageId: "MI0001",
      name: "Trip 5",
      description: "Weekend trip Rome",
      image: "Italy.jpeg",
      country: "Italy",
      price: 678.99,
      discount: 25,
      quantity: 12,
      rating: 3,
      departure: "2023-05-20",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[4]._id,
    },
    {
      packageId: "CA0001",
      name: "Trip 6",
      description: "Weekend trip Toronto",
      image: "Canada.jpeg",
      country: "Canada",
      price: 1235.99,
      discount: 25,
      quantity: 6,
      rating: 4,
      departure: "2023-06-14",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[5]._id,
    },
    {
      packageId: "PO0001",
      name: "Trip 7",
      description: "Weekend trip poland",
      image: "Poland.jpeg",
      country: "Poland",
      price: 1543.99,
      discount: 25,
      quantity: 13,
      rating: 4,
      departure: "2023-07-21",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[4]._id,
    },
    {
      packageId: "BR0001",
      name: "Trip 8",
      description: "Weekend trip Brazil",
      image: "Brazil.jpeg",
      country: "Brazil",
      price: 456.99,
      discount: 25,
      quantity: 4,
      rating: 3,
      departure: "2023-07-8",
      duration: 2,
      allinclusive: false,
      activities: false,
      category: categories[7]._id,
    },
    {
      packageId: "PE0001",
      name: "Trip 9",
      description: "Weekend trip Peru",
      image: "Peru.jpeg",
      country: "Peru",
      price: 321.99,
      discount: 25,
      quantity: 2,
      rating: 4,
      departure: "2023-07-12",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[7]._id,
    },
    {
      packageId: "CH0001",
      name: "Trip 10",
      description: "Weekend trip Chile",
      image: "Chile.jpeg",
      country: "chile",
      price: 564.99,
      discount: 25,
      quantity: 8,
      rating: 3,
      departure: "2023-06-5",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[7]._id,
    },
    {
      packageId: "EC0001",
      name: "Trip 11",
      description: "Weekend trip Ecuador",
      image: "Ecuador.jpeg",
      country: "Ecuador",
      price: 473.99,
      discount: 25,
      quantity: 17,
      rating: 3,
      departure: "2023-07-23",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[7]._id,
    },
    {
      packageId: "PA0001",
      name: "Trip 12",
      description: "Weekend trip Panama",
      image: "Panama.jpeg",
      country: "Panama",
      price: 684.99,
      discount: 25,
      quantity: 3,
      rating: 3,
      departure: "2023-07-11",
      duration: 2,
      allinclusive: true,
      activities: false,
      category: categories[3]._id,
    },
    {
      packageId: "ME0001",
      name: "Trip 13",
      description: "Weekend trip mexico",
      image: "Mexico.jpeg",
      country: "Mexico",
      price: 521.99,
      discount: 25,
      quantity: 1,
      rating: 4,
      departure: "2023-08-11",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[3]._id,
    },
    {
      packageId: "MO0001",
      name: "Trip 14",
      description: "Weekend trip moroco",
      image: "Morocco.jpeg",
      country: "Moroco",
      price: 621.99,
      discount: 25,
      quantity: 3,
      rating: 4,
      departure: "2023-07-18",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[0]._id,
    },
    {
      packageId: "SA0001",
      name: "Trip 15",
      description: "Weekend trip south africa",
      image: "Southafrica.jpeg",
      country: "SouthAfrica",
      price: 1432.99,
      discount: 25,
      quantity: 6,
      rating: 4,
      departure: "2023-07-6",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[0]._id,
    },
    {
      packageId: "KE0001",
      name: "Trip 16",
      description: "Weekend trip Kenya",
      image: "Kenya.jpeg",
      country: "Kenya",
      price: 578.99,
      discount: 25,
      quantity: 4,
      rating: 2,
      departure: "2023-07-1",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[0]._id,
    },
    {
      packageId: "IR0001",
      name: "Trip 17",
      description: "Weekend trip Iran",
      image: "Iran.jpeg",
      country: "Iran",
      price: 1452.99,
      discount: 25,
      quantity: 10,
      rating: 5,
      departure: "2023-08-1",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[1]._id,
    },
    {
      packageId: "TU0001",
      name: "Trip 18",
      description: "Weekend trip Turkey",
      image: "Turkey.jpeg",
      country: "Turkey",
      price: 1152.99,
      discount: 25,
      quantity: 5,
      rating: 4,
      departure: "2023-07-3",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[1]._id,
    },
    {
      packageId: "JA0001",
      name: "Trip 19",
      description: "Weekend trip Japan",
      image: "Japan.jpeg",
      country: "Japan",
      price: 1232.99,
      discount: 25,
      quantity: 7,
      rating: 5,
      departure: "2023-07-20",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[1]._id,
    },
    {
      packageId: "CH0001",
      name: "Trip 20",
      description: "Weekend trip China",
      image: "China.jpeg",
      country: "China",
      price: 985.99,
      discount: 25,
      quantity: 2,
      rating: 3,
      departure: "2023-07-14",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[1]._id,
    },
    {
      packageId: "BA0001",
      name: "Trip 21",
      description: "Weekend trip the bahamas",
      image: "TheBahamas.jpeg",
      country: "The Bahamas",
      price: 874.99,
      discount: 25,
      quantity: 17,
      rating: 2,
      departure: "2023-07-23",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[2]._id,
    },
    {
      packageId: "AU0001",
      name: "Trip 22",
      description: "Weekend trip Australia",
      image: "Australia.jpeg",
      country: "Australia",
      price: 976.99,
      discount: 25,
      quantity: 5,
      rating: 4,
      departure: "2023-07-21",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[6]._id,
    },
    {
      packageId: "NZ0001",
      name: "Trip 23",
      description: "Weekend trip New Zealand",
      image: "Newzealand.jpeg",
      country: "New Zealand",
      price: 1132.99,
      discount: 25,
      quantity: 25,
      rating: 4,
      departure: "2023-07-27",
      duration: 2,
      allinclusive: true,
      activities: true,
      category: categories[6]._id,
    },
  ]);

  console.log("products seeded");

  await User.deleteMany();

  await User.create({
    firstName: "Shohei",
    lastName: "Mochizuki",
    email: "smochizuki@gmail.com",
    password: "password",
    orders: [
      {
        products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
    savedProducts: [products[1]._id],
  });

  await User.create({
    firstName: "Test",
    lastName: "Test",
    email: "test@gmail.com",
    password: "password",
    orders: [],
    savedProducts: [products[0]._id, products[1]._id],
  });

  console.log("users seeded");

  process.exit();
});
